### ISSUE TITLE
Cannot run composer install during setup

### ISSUE THREAD

**Issue by davidpiesse** [spatie/skeleton-nova-tool#2]
I have run through the skeleton setup and have gotten to the composer stage.

I am getting an error around the laravel/nova package

**Your requirements could not be resolved to an installable set of packages.**
_Problem 1
    - The requested package laravel/nova could not be found in any version, there may be a typo in the package name._

Does Laravel Nova need to be referenced from elsewhere; or have I had a silly moment and missed something?

**Comment by KABBOUCHI** [comment]
make sure to update nova path
https://github.com/spatie/skeleton-nova-tool/blob/155ce65ef058adbc2b5daac0350127a63c9f0deb/composer.json#L8-L12

**Comment by davidpiesse** [comment]
Bingo - thanks - copied the nova dir to the root and then gitignored it.
Is this in the docs?

**Comment by davidpiesse** [comment]
Cheers All - Yeah.
Maybe in the docs if you reference your new tool in your benchtest app before the composer install it would make more sense?
⚡️

**Comment by freekmurze** [comment]
Feel free to send PRs to the readme of this repo to improve the experience for other users of this skeleton.

**Comment by tomhatzer** [comment]
Tried to rephrase the README.md in https://github.com/spatie/skeleton-nova-tool/pull/3
