### ISSUE TITLE
Authorize Middleware

### ISSUE THREAD

**Issue by marianvlad** [spatie/skeleton-nova-tool#4]
Working on my package because [this issue](https://github.com/marianvlad/nova-env-card/issues/1) and trying to find a way to secure routes for my card I implemented the Authorize Middleware, but after some tests I found that [`app(Tool::class)->authorize($request)`](https://github.com/spatie/skeleton-nova-tool/blob/master/src/Http/Middleware/Authorize.php#L14) does nothing because `app(Tool::class)` it's a new instance of the class and the authorization method canSee() put in `App\Providers\NovaServiceProvider` does nothing. e.g 
```php
(new \Spatie\BackupTool\BackupTool())->canSee(function ($request) {
    return false;
}),
```

For my card I implemented the code below. I don't know if is the best way to solve the problem but it works.
```php
public function handle(Request $request, Closure $next)
{
    return $this->isAuthorized(NovaEnvCard::class, $request)
        ? $next($request)
        : abort(403);
}

protected function isAuthorized($class, $request)
{
	return collect(
		array_merge(
			Nova::availableCards($request),
			Nova::availableTools($request)
		))->first(function ($value, $key) use ($class) {
			return $class == get_class($value);
		}) ?: false;
}
```

**Comment by freekmurze** [comment]
Thanks for reporting this, I can reproduce the problem and am currently investigating a good solution.
